# Generated by Django 4.2.17 on 2025-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ra", models.CharField(max_length=20)),
                ("dec", models.CharField(max_length=20)),
                ("file_source", models.FileField(upload_to="candidate_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
